
// Extracted from f-stop.vercel.app HTML source

export interface PresetData {
    id: string;
    title: string;
    category: string;
    desc: string;
    data: {
        genre?: string;
        camera?: string;
        lens?: string;
        focal?: number;
        aperture?: string;
        shutter?: string;
        iso?: string;
        lighting?: string;
        composition?: string;
        lightingSetups?: string[];
        vibe?: string;
        lensChar?: string;
        film?: string;
        wb?: string;
        grain?: string;
        productSubgenre?: string;
    };
}

export const BASE_PRESETS: PresetData[] = [
    { id: "none", title: "None", desc: "Manual mode", category: "Core", data: {} },

    // STREET
    { id: "leiter-street", "title": "Saul Leiter", "category": "Street", "desc": "Reflections, layered color panes.", "data": { "genre": "abstract street", "camera": "Leica M3", "lens": "90mm Elmar f/4", "focal": 90, "aperture": "f/4", "shutter": "1/60s", "iso": "25", "lighting": "Available Light", "composition": "Layered Abstraction", "lightingSetups": ["rainy overcast daylight", "neon reflections on wet asphalt", "window condensation"], "vibe": "Saul Leiter style, painterly aesthetic, shooting through obstructions (steam, rain, windows), telephoto compression, flattened perspective, muted reds and deep blacks.", "lensChar": "Vintage Low Contrast", "film": "Kodachrome", "wb": "Daylight", "grain": "Fine" } },
    { id: "cartier-bresson", title: "Henri Cartier-Bresson", category: "Street", desc: "The decisive moment.", data: { genre: "street", camera: "Leica M3 (35mm rangefinder, black paint)", lens: "Leitz Summicron 50mm f/2 (collapsible)", focal: 50, aperture: "f/8", shutter: "1/125s", iso: "400", lighting: "Available light (natural)", composition: "Geometry & layered framing", vibe: "Decisive-moment street reportage, eye-level candor, clean silhouettes, balanced negative space, strong geometry, minimal cropping aesthetic.", lensChar: "High micro-contrast, gentle flare/halation, subtle vignetting", film: "Kodak Tri-X 400 (35mm B&W)", wb: "B&W (N/A)", grain: "Classic pronounced grain" } },
    { id: "moriyama-flash", title: "Daido Moriyama", category: "Street", desc: "High contrast grit.", data: { genre: "street", camera: "Ricoh GR21", lens: "28mm prime", focal: 28, aperture: "f/11", shutter: "1/60s", iso: "1600", lighting: "Direct Flash", composition: "Tight Close-up", lightingSetups: ["hard direct flash, fast falloff shadows"], vibe: "Daido Moriyama style, aggressive close range flash, blur and grain embraced, high contrast blacks, cropped bodies and signage, restless night street energy.", lensChar: "Heavy Vignette", film: "Kodak Tri-X 400", wb: "Mixed Lighting", grain: "Heavy Grit" } },
    { id: "eggleston-color", title: "William Eggleston", category: "Street", desc: "Saturated color, mundane iconic.", data: { genre: "street", camera: "Leica M3", lens: "50mm prime", focal: 50, aperture: "f/8", shutter: "1/250s", iso: "100", lighting: "Natural Light", composition: "Rule of Thirds", vibe: "William Eggleston style, vivid but believable color, quiet mundane subjects, southern daylight, dye-transfer print look.", lensChar: "Vintage Softness", film: "Kodachrome 64", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "webb-layered", title: "Alex Webb", category: "Street", desc: "Dense frames, hot color, shadows.", data: { genre: "street", camera: "Leica M6", lens: "35mm prime", focal: 35, aperture: "f/8", shutter: "1/500s", iso: "100", lighting: "Golden Hour", composition: "Layered Depth", vibe: "Alex Webb style, complex multi-subject street scenes, saturated color in harsh light, deep shadow zones, complex layering.", lensChar: "Clinical Sharp", film: "Kodachrome 64", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "weegee-noir", title: "Weegee", category: "Street", desc: "Hard flash night noir.", data: { genre: "night", camera: "Speed Graphic 4x5", lens: "127mm Ektar", focal: 127, aperture: "f/11", shutter: "1/200s", iso: "100", lighting: "Direct Flash", composition: "Tight Close-up", lightingSetups: ["hard direct flash, fast falloff shadows"], vibe: "Weegee style, hard on-camera flash bulb, gritty nocturnal realism, high contrast blacks, crime scene aesthetic, near-black backgrounds.", lensChar: "Vintage Softness", film: "B&W Sheet Film", wb: "Mixed Lighting", grain: "Heavy Grit" } },
    { id: "mccurry-travel", title: "Steve McCurry", category: "Street", desc: "Vivid travel portraits.", data: { genre: "street", camera: "Nikon F6", lens: "105mm prime", focal: 105, aperture: "f/2.8", shutter: "1/250s", iso: "64", lighting: "Natural Light", composition: "Rule of Thirds", vibe: "Steve McCurry style, saturated yet believable color, intimate travel portraiture, strong eye contact, warm daylight, Kodachrome aesthetic.", lensChar: "Clinical Sharp", film: "Kodachrome 64", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "salgado-humanity", title: "Sebastião Salgado", category: "Street", desc: "Dramatic B&W documentary.", data: { genre: "street", camera: "Pentax 645", lens: "45-85mm zoom", focal: 45, aperture: "f/8", shutter: "1/250s", iso: "400", lighting: "Natural Light", composition: "Rule of Thirds", vibe: "High-contrast humanist reportage, strong silhouettes, epic scale, deep blacks and rich mid-tones, silver gelatin print look.", lensChar: "Clinical Sharp", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Medium Texture" } },

    // PORTRAIT & FASHION
    { id: "lindbergh-raw", title: "Peter Lindbergh", category: "Portrait & Fashion", desc: "Raw B&W realism, negative fill.", data: { genre: "portrait", camera: "Nikon F5", lens: "85mm prime", focal: 85, aperture: "f/2.8", shutter: "1/250s", iso: "400", lighting: "Soft Overcast", composition: "Centered", lightingSetups: ["window side light, soft falloff", "negative fill, black flags, light subtraction"], vibe: "Peter Lindbergh style, raw emotive portrait realism, natural skin texture, minimal retouch, strong eye contact, wind-blown hair, coastal or industrial backdrops, high contrast monochrome, rich blacks.", lensChar: "Vintage Softness", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Medium Texture" } },
    { id: "weir-soft", title: "Harley Weir", category: "Portrait & Fashion", desc: "Soft daylight, intimate warmth.", data: { genre: "portrait", camera: "Pentax 67", lens: "105mm prime", focal: 105, aperture: "f/2.4", shutter: "1/125s", iso: "400", lighting: "Natural Light", composition: "Tight Close-up", lightingSetups: ["window side light, soft falloff"], vibe: "Harley Weir style, soft warm natural light, intimate close distance, focus on sensory details (skin, fabric), shallow depth of field with 3D pop, gentle color, candid energy, editorial but lived-in mood.", lensChar: "Dreamy Bloom", film: "Kodak Portra 400", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "leibovitz-celeb", title: "Annie Leibovitz", category: "Portrait & Fashion", desc: "Theatrical staged storytelling with a painterly touch.", data: { genre: "environmental portrait", camera: "Hasselblad H6D", lens: "50mm (35mm Equiv.)", focal: 50, aperture: "f/8", shutter: "1/160s", iso: "100", lighting: "Large Octabank or Photek Softlighter", composition: "Environmental Portrait / Tableau", lightingSetups: ["Large feathered light source (Octabank/Softlighter)", "Subject placed at edge of light falloff", "Negative fill for contrast"], vibe: "Painterly Vanity Fair aesthetic, muted desaturated greens, cyan/blue-tinted shadows, warm skin tones, rich canvas-like textures, dramatic environmental context.", lensChar: "High Fidelity / Painterly Softness", film: "Medium Format Digital", wb: "Daylight Balanced", grain: "Fine/Low Grain" } }, { id: "avedon-highkey", title: "Richard Avedon", category: "Portrait & Fashion", desc: "White background, crisp gestures.", data: { genre: "portrait", camera: "Deardorff 8x10", lens: "360mm prime", focal: 360, aperture: "f/32", shutter: "1/125s", iso: "400", lighting: "High Key White Cyc", composition: "Centered", lightingSetups: ["high key white cyc, even wraparound light"], vibe: "Richard Avedon style, stark minimalism, pure white seamless background, 8x10 large format contact print aesthetic, visible black film borders (rebate edge), uncompromising sharpness, expressive gesture, high contrast black and white.", lensChar: "Clinical Sharp", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "newton-edgy", title: "Helmut Newton", category: "Portrait & Fashion", desc: "Hard ring flash, statuesque poses.", data: { genre: "portrait", camera: "Hasselblad 500C/M", lens: "80mm prime", focal: 80, aperture: "f/11", shutter: "1/125s", iso: "100", lighting: "Ring Light", composition: "Low Angle Hero", lightingSetups: ["ring light fill"], vibe: "Helmut Newton style, 'Porno-chic' aesthetic, hard ring flash lighting creating a distinct shadow halo on the wall, glossy/oily skin texture, statuesque Amazonian women, low angle empowerment, cold eroticism, high contrast color reversal film.", lensChar: "Clinical Sharp", film: "Kodak Ektachrome E100", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "platon-close", title: "Platon", category: "Portrait & Fashion", desc: "Intense wide-angle close-ups.", data: { genre: "portrait", camera: "Hasselblad 555ELD", lens: "30mm Zeiss Distagon T* Fisheye", focal: 30, aperture: "f/16", shutter: "1/500s", iso: "400", lighting: "Hard Strobe (Zoom Reflector)", composition: "Centered / Floating Head", lightingSetups: ["Hard butterfly lighting", "Single strobe with zoom reflector on-axis", "Heavy vignetting on white background"], vibe: "Platon style, 30mm fisheye on medium format (extreme barrel distortion), camera inches from subject, bulbous nose and intense eyes while ears recede, high-contrast monochrome, geological skin texture, confrontational gaze.", lensChar: "Distorted & Sharp", film: "Kodak Tri-X 400 (Pushed)", wb: "Monochrome", grain: "Heavy Silver Halide" } },
    { id: "testino-fashion", title: "Mario Testino", category: "Portrait & Fashion", desc: "High-voltage glamour and kinetic energy.", data: { genre: "portrait", camera: "Pentax 67II", lens: "SMC Pentax 55mm f/4", focal: 55, aperture: "f/11", shutter: "1/125s", iso: "100", lighting: "Direct Ring Flash / Hard Strobe", composition: "Dynamic/Snapshot", lightingSetups: ["Direct on-axis hard flash", "Shadows falling directly behind subject", "High specular highlights on skin"], vibe: "Mario Testino style, Gucci era aesthetic, wide-angle medium format, hard flash creating distinct drop shadows, hyper-saturated skin tones, oiled/glossy texture, hedonistic atmosphere, sharp foreground with vibrant colors.", lensChar: "High Contrast & Saturated", film: "Fujichrome Velvia 50", wb: "Flash Balanced", grain: "Fine Color Grain" } },
    { id: "walker-surreal", title: "Tim Walker", category: "Portrait & Fashion", desc: "Whimsical theatrical surrealism.", data: { genre: "portrait", camera: "Pentax 67II", lens: "SMC Pentax 45mm f/4", focal: 45, aperture: "f/4", shutter: "1/30s", iso: "400", lighting: "Natural Window Light / Diffused HMI", composition: "Wide Tableau", lightingSetups: ["Soft directional window light", "Overexposed highlights", "Negative fill"], vibe: "Tim Walker style, storybook surrealism, crumbling English architecture, oversized practical props (no CGI), distorted scale, romantic decaying grandeur, milky pastel colors, soft focus falloff.", lensChar: "Painterly & Soft", film: "Kodak Portra 400NC (Overexposed)", wb: "Daylight Balanced", grain: "Organic Medium" } },
    { id: "bourdin-surreal", title: "Guy Bourdin", category: "Portrait & Fashion", desc: "Saturated, narrative surrealism with a voyeuristic edge.", data: { genre: "portrait", camera: "Pentax 67", lens: "SMC Pentax 55mm f/4", focal: 55, aperture: "f/16", shutter: "1/125s", iso: "64", lighting: "Hard Direct Flash / Harsh Sunlight", composition: "Voyeuristic/Cropped", lightingSetups: ["Direct on-axis strobe", "Deep defined cast shadows", "High contrast sun-drenched"], vibe: "Guy Bourdin style, voyeuristic narrative, fragmented bodies (cropped heads/limbs), hyper-saturated Kodachrome colors (deep blues and lipstick reds), ominous or surreal atmosphere, glossy magazine finish, infinite depth of field.", lensChar: "Sharp & High Contrast", film: "Kodachrome 64", wb: "Daylight Balanced", grain: "Very Fine" } },
    // CINEMATIC
    { id: "deakins-cine", title: "Roger Deakins", category: "Cinematic", desc: "Naturalistic film precision.", data: { genre: "cinematic", camera: "Arri Alexa 35", lens: "32mm prime", focal: 32, aperture: "f/2.8", shutter: "1/48s", iso: "800", lighting: "Neon Practical", composition: "Leading Lines", lightingSetups: ["window side light, soft falloff"], vibe: "Roger Deakins style, grounded cinematic realism, subtle contrast, motivated practical light, careful negative fill, clean compositions, atmospheric depth without exaggeration.", lensChar: "Clinical Sharp", film: "Kodak Vision3 500T (5219)", wb: "Mixed Lighting", grain: "Subtle Grain" } },
    { id: "doyle-neon", title: "Christopher Doyle", category: "Cinematic", desc: "Neon wash, rain, handheld.", data: { genre: "cinematic", camera: "Arriflex 35 BL", lens: "32mm prime", focal: 32, aperture: "f/2", shutter: "1/48s", iso: "500", lighting: "Neon Practical", composition: "Rule of Thirds", vibe: "Christopher Doyle style, saturated neon color wash, rainy streets, handheld intimacy, motion blur as emotion, step printing effect.", lensChar: "Vintage Softness", film: "Kodak Vision3 500T (5219)", wb: "Mixed Lighting", grain: "Medium Texture" } },
    { id: "crewdson-tableau", title: "Gregory Crewdson", category: "Cinematic", desc: "Staged suburban eeriness.", data: { genre: "cinematic", camera: "Phase One XF IQ4", lens: "35mm prime", focal: 35, aperture: "f/11", shutter: "1/2s", iso: "100", lighting: "Natural Light", composition: "Wide Establishing", lightingSetups: ["softbox key plus bounce"], vibe: "Gregory Crewdson style, staged cinematic suburbia, eerie calm, fog or haze, practical motivated light, meticulous tableau framing, high budget production design.", lensChar: "Clinical Sharp", film: "Kodak Portra 400", wb: "Mixed Lighting", grain: "Subtle Grain" } },
    { id: "anderson-symmetry", title: "Wes Anderson", category: "Cinematic", desc: "Symmetrical, pastel, flat.", data: { genre: "cinematic", camera: "Arricam ST", lens: "40mm anamorphic", focal: 40, aperture: "f/5.6", shutter: "1/48s", iso: "200", lighting: "Soft Overcast", composition: "Symmetrical Arch", lightingSetups: ["high key white cyc, even wraparound light"], vibe: "Wes Anderson style (Robert Yeoman), perfectly symmetrical composition, flat planar staging, pastel color palette, whimsical attention to detail, soft even lighting, storybook aesthetic.", lensChar: "Clinical Sharp", film: "Kodak Vision3 200T (5213)", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "kubrick-perspective", title: "Stanley Kubrick", category: "Cinematic", desc: "One-point perspective, clinical.", data: { genre: "cinematic", camera: "Arriflex 35 BL", lens: "18mm prime", focal: 18, aperture: "f/0.7", shutter: "1/48s", iso: "100", lighting: "Candlelight", composition: "Centered", lightingSetups: ["practical lighting"], vibe: "Stanley Kubrick style, obsessive one-point perspective, clinical detachment, deep focus or extreme shallow (Barry Lyndon), Steadicam fluidity, uncanny symmetry, cold or high-contrast practical lighting.", lensChar: "Clinical Sharp", film: "Kodak 5247 100T (70s/80s)", wb: "Cool Shade", grain: "Subtle Grain" } },
    { id: "fraser-darkness", title: "Greig Fraser", category: "Cinematic", desc: "Modern dark epic (Dune/Batman).", data: { genre: "cinematic", camera: "Arri Alexa LF", lens: "50mm anamorphic", focal: 50, aperture: "f/2.8", shutter: "1/48s", iso: "1600", lighting: "Soft Overcast", composition: "Rule of Thirds", lightingSetups: ["soft top down ambient"], vibe: "Greig Fraser style, modern dark epic cinematography, soft falloff, rich blacks, textured shadows, atmospheric haze, grounded sci-fi realism, anamorphic depth, distinct oval bokeh.", lensChar: "Vintage Softness", film: "Kodak Vision3 500T (5219)", wb: "Daylight Balanced", grain: "Medium Texture" } },
    { id: "scott-atmosphere", title: "Ridley Scott", category: "Cinematic", desc: "Atmospheric shafts of light, industrial haze.", data: { genre: "cinematic", camera: "Arriflex 35 BL", lens: "50mm anamorphic", focal: 50, aperture: "f/2.8", shutter: "1/48s", iso: "100", lighting: "Neon Practical", composition: "Layered Depth", lightingSetups: ["atmospheric smoke and light shafts", "backlit translucent diffusion, soft halos"], vibe: "Ridley Scott style (Blade Runner/Alien), dense atmospheric layering, smoke and haze, distinct shafts of light (god rays), high contrast, industrial texture, anamorphic lens flares, cyan and orange grading, chiaroscuro.", lensChar: "Gentle Halation", film: "Kodak 5247 100T (70s/80s)", wb: "Mixed Lighting", grain: "Medium Texture" } },
    { id: "lubezki-natural", title: "Emmanuel Lubezki", category: "Cinematic", desc: "Immersive wide-angle naturalism.", data: { genre: "cinematic", camera: "Arri Alexa 65", lens: "14mm prime", focal: 14, aperture: "f/5.6", shutter: "1/48s", iso: "800", lighting: "Natural Light", composition: "Layered Depth", lightingSetups: [], vibe: "Emmanuel Lubezki style (The Revenant/Birdman), extreme wide angle close-up, immersive proximity, natural light only (magic hour or overcast), cold blue tones contrasting with warm breath/fire, hyper-realistic resolution, floating camera movement.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "storaro-period", title: "Vittorio Storaro", category: "Cinematic", desc: "Operatic light, rich color symbolism.", data: { genre: "cinematic", camera: "Arriflex 35 BL", lens: "40mm anamorphic", focal: 40, aperture: "f/4", shutter: "1/48s", iso: "100", lighting: "Golden Hour", composition: "Symmetrical Arch", lightingSetups: ["atmospheric smoke and light shafts", "high contrast rim lighting"], vibe: "Vittorio Storaro style (Apocalypse Now), writing with light, operatic high contrast, rich color symbolism (orange vs blue), Technovision anamorphic flares, epic scale chiaroscuro.", lensChar: "Clinical Sharp", film: "Kodak 5247 100T (70s/80s)", wb: "Warm Tungsten", grain: "Subtle Grain" } },
    { id: "kurosawa-epic", title: "Akira Kurosawa", category: "Cinematic", desc: "Extreme telephoto compression, dynamic weather.", data: { genre: "cinematic", camera: "Mitchell BNC", lens: "500mm tele", focal: 500, aperture: "f/11", shutter: "1/48s", iso: "200", lighting: "Natural Light", composition: "Wide Establishing", lightingSetups: [], vibe: "Akira Kurosawa style (Seven Samurai), extreme telephoto compression flattening the perspective, geometric composition of armies/crowds, dynamic weather (rain/fog/wind), motion blur in background, high contrast monochrome.", lensChar: "Vintage Softness", film: "Eastman Double-X 5222", wb: "Daylight Balanced", grain: "Medium Texture" } },
    // ANALOG VAULT
    { id: "wet-plate", title: "Wet Plate Collodion", category: "Analog Vault", desc: "1850s ghostly chemical imperfection.", data: { genre: "portrait", camera: "Large Format 8x10", lens: "300mm prime", focal: 300, aperture: "f/5.6", shutter: "4s", iso: "1", lighting: "Natural Light", composition: "Centered", lightingSetups: ["window side light, soft falloff"], vibe: "Wet plate collodion process (1850s), ghostly silver nitrate texture, chemical stains and poured edges, extremely shallow depth of field, eyes rendered pale/white due to UV sensitivity, antique sepia monochrome.", lensChar: "Vintage Softness", film: "Wet Plate Collodion", wb: "Cool Shade", grain: "Heavy Grit" } },
    { id: "kodachrome-64", title: "Kodachrome 64", category: "Analog Vault", desc: "The National Geographic look.", data: { genre: "street", camera: "Nikon F3", lens: "35mm prime", focal: 35, aperture: "f/5.6", shutter: "1/125s", iso: "64", lighting: "Natural Light", composition: "Rule of Thirds", lightingSetups: [], vibe: "Kodachrome 64 film stock, iconic National Geographic aesthetic (80s), deep rich reds and yellows, high contrast, distinct archival sharpness, nostalgic vacation mood.", lensChar: "Clinical Sharp", film: "Kodachrome 64", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "solarization", title: "Solarization (Man Ray)", category: "The Darkroom", desc: "Surreal inverted highlights.", data: { genre: "portrait", camera: "Large Format 4x5", lens: "150mm prime", focal: 150, aperture: "f/11", shutter: "1s", iso: "10", lighting: "Hard Strobe", composition: "Centered", lightingSetups: ["high contrast rim lighting"], vibe: "Solarization effect (Sabattier effect), surreal reversal of tone, metallic skin, dark outlines around highlights, dreamlike high contrast monochrome.", lensChar: "Clinical Sharp", film: "Kodak Tri-X 400", wb: "Cool Shade", grain: "Medium Texture" } },
    { id: "cyanotype", title: "Cyanotype (Blueprint)", category: "The Darkroom", desc: "Deep Prussian blue monochrome.", data: { genre: "experimental", camera: "Contact Print", lens: "None", focal: 0, aperture: "None", shutter: "30s", iso: "1", lighting: "Natural Light", composition: "Top-down Flat Lay", lightingSetups: [], vibe: "Cyanotype print, deep Prussian blue and white monochrome, high contrast, architectural blueprint aesthetic, botanical textures, sun-printed look.", lensChar: "Vintage Softness", film: "None", wb: "Cool Shade", grain: "Heavy Grit" } },
    { id: "cross-process", title: "Cross-Processed", category: "The Darkroom", desc: "90s skate style, skewed colors.", data: { genre: "street", camera: "Contax T2", lens: "38mm prime", focal: 38, aperture: "f/5.6", shutter: "1/250s", iso: "400", lighting: "Direct Flash", composition: "Low Angle Hero", lightingSetups: ["hard direct flash, fast falloff shadows"], vibe: "Cross-processed film look (slide film in C-41 chemicals), high contrast, skewed colors with yellow highlights and blue shadows, 90s skate magazine aesthetic.", lensChar: "Clinical Sharp", film: "Kodak Ektachrome E100", wb: "Mixed Lighting", grain: "Medium Texture" } },

    // GENRE CINEMA
    { id: "cyberpunk-neon", title: "Cyberpunk / Neo-Noir", category: "Genre Cinema", desc: "Rain, neon, high tech, low life.", data: { genre: "night", camera: "Arri Alexa LF", lens: "35mm anamorphic", focal: 35, aperture: "f/2", shutter: "1/48s", iso: "800", lighting: "Neon Practical", composition: "Leading Lines", lightingSetups: ["neon sign spill", "atmospheric smoke and light shafts"], vibe: "Cyberpunk Neo-Noir aesthetic (Blade Runner 2049), rain-slicked streets reflecting pink and cyan neon, deep blacks, wet pavement texture, steam vents, futuristic urban decay, anamorphic lens flares, halation around light sources.", lensChar: "Gentle Halation", film: "Kodak Vision3 500T (5219)", wb: "Mixed Lighting", grain: "Medium Texture" } },
    { id: "folk-horror", title: "Folk Horror", category: "Genre Cinema", desc: "Dread in bright daylight.", data: { genre: "cinematic", camera: "Arri Alexa 35", lens: "24mm prime", focal: 24, aperture: "f/11", shutter: "1/48s", iso: "50", lighting: "Direct Sunlight", composition: "Symmetrical Arch", lightingSetups: [], vibe: "Folk Horror aesthetic (Midsommar style), uncomfortably bright daylight, pastel florals, white linens, blinding sun, pagan symbolism, dread concealed by beauty, overexposed highlights, deep depth of field.", lensChar: "Clinical Sharp", film: "Kodak Vision3 250D (5207)", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "space-opera", title: "Space Opera (70s)", category: "Genre Cinema", desc: "Practical models, lens flares.", data: { genre: "cinematic", camera: "Panavision PSR", lens: "50mm anamorphic", focal: 50, aperture: "f/4", shutter: "1/48s", iso: "100", lighting: "Studio Hard Light", composition: "Wide Establishing", lightingSetups: ["rim light, edge definition"], vibe: "70s Space Opera aesthetic (Star Wars / Alien), practical scale models, kitbashing textures, star fields, sterile white corridors, industrial sci-fi, blue anamorphic lens flares, matte painting backgrounds, motion control look.", lensChar: "Vintage Softness", film: "Kodak 5247 100T (70s/80s)", wb: "Daylight Balanced", grain: "Medium Texture" } }, { id: "fisheye-90s", title: "Fisheye (90s Music Video)", category: "Extreme Perspectives", desc: "Circular distortion, Hype Williams style.", data: { genre: "experimental", camera: "Sony VX1000", lens: "8mm fisheye", focal: 8, aperture: "f/4", shutter: "1/60s", iso: "400", lighting: "Ring Light", composition: "Tight Close-up", lightingSetups: [], vibe: "Fisheye lens distortion, Hype Williams music video aesthetic (90s), massive barrel distortion, exaggerated close-up features, circular vignette, MiniDV tape texture, scanlines.", lensChar: "Chromatic Aberration", film: "Digital Video Tape (DV)", wb: "Mixed Lighting", grain: "Medium Texture" } },
    { id: "drone-topdown", title: "Top-Down Drone", category: "Extreme Perspectives", desc: "God's eye view geometry.", data: { genre: "landscape", camera: "DJI Mavic 3", lens: "24mm prime", focal: 24, aperture: "f/5.6", shutter: "1/1000s", iso: "100", lighting: "Direct Sunlight", composition: "Top-down Flat Lay", lightingSetups: [], vibe: "Top-down aerial drone photography (Nadir view), orthographic projection, perfect geometric patterns, flat lay landscape, high altitude perspective, even sharpness edge-to-edge, geometric abstraction.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "micro-macro", title: "Micro-Macro (Insect Eye)", category: "Extreme Perspectives", desc: "Alien textures, razor depth.", data: { genre: "wildlife", camera: "Canon EOS R5 II", lens: "100mm macro", focal: 100, aperture: "f/11", shutter: "1/200s", iso: "100", lighting: "Ring Light", composition: "Tight Close-up", lightingSetups: [], vibe: "Extreme macro photography, 2:1 magnification, alien textures of insect compound eyes, hexagonal grid patterns, iridescent chitin, razor-thin depth of field (focus stacked), metallic sheen, hyper-detailed.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } }, { id: "technicolor", title: "Technicolor 3-Strip", category: "Color Eras", desc: "Hyper-saturated 1939 look.", data: { genre: "cinematic", camera: "Technicolor 3-Strip Camera", lens: "35mm prime", focal: 35, aperture: "f/4", shutter: "1/48s", iso: "5", lighting: "Studio Hard Light", composition: "Centered", lightingSetups: ["high key white cyc, even wraparound light"], vibe: "Technicolor 3-Strip process (Wizard of Oz era), Dye-transfer print look, hyper-saturated unreal reds and emerald greens, peaches and cream skin tones, deep depth of field, high intensity carbon arc lighting aesthetic.", lensChar: "Clinical Sharp", film: "Technicolor Three-Strip", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "autochrome", title: "Autochrome Lumière", category: "Color Eras", desc: "1907 pointillist potato starch.", data: { genre: "portrait", camera: "Large Format 4x5", lens: "150mm prime", focal: 150, aperture: "f/8", shutter: "2s", iso: "1", lighting: "Natural Light", composition: "Centered", lightingSetups: [], vibe: "Autochrome Lumière (1907), microscopic dyed potato starch grain structure, pointillist painterly aesthetic, muted pastel colors, soft focus, heavy vignetting, low dynamic range, ethereal dreamlike quality.", lensChar: "Vintage Softness", film: "Autochrome Plate", wb: "Daylight Balanced", grain: "Heavy Grit" } },
    { id: "infrared-aero", title: "Infrared Aerochrome", category: "Experimental", desc: "Surreal pink foliage, false color.", data: { genre: "landscape", camera: "Hasselblad 500C/M", lens: "50mm prime", focal: 50, aperture: "f/8", shutter: "1/250s", iso: "400", lighting: "Direct Sunlight", composition: "Wide Establishing", lightingSetups: [], vibe: "Kodak Aerochrome 1443 (EIR), false color infrared photography, chlorophyll/foliage rendered as vibrant crimson red or bubblegum pink, Wratten 12 yellow filter effect (creating deep navy blue skies), high contrast, surreal psychedelic landscape.", lensChar: "Clinical Sharp", film: "Kodak Aerochrome (IR)", wb: "Daylight Balanced", grain: "Medium Texture" } },
    { id: "tilt-shift-mini", title: "Tilt-Shift Miniature", category: "Experimental", desc: "Faking a miniature world.", data: { genre: "architecture", camera: "Canon EOS R5 II", lens: "45mm tilt-shift", focal: 45, aperture: "f/2.8", shutter: "1/500s", iso: "100", lighting: "Direct Sunlight", composition: "High Angle (Bird's Eye)", lightingSetups: [], vibe: "Tilt-Shift photography, selective focus plane, blurring top and bottom to create a miniature 'toy world' effect, isometric perspective, high saturation, vibrant colors, hard shadows like a model set.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "double-exposure", title: "Double Exposure", category: "Experimental", desc: "Silhouette landscape blend.", data: { genre: "portrait", camera: "Canon EOS 5D Mark IV", lens: "50mm prime", focal: 50, aperture: "f/8", shutter: "1/125s", iso: "100", lighting: "High Key White Cyc", composition: "Side Profile", lightingSetups: ["high key white cyc, even wraparound light"], vibe: "Double Exposure art, silhouette of a subject's side profile filled with a secondary landscape image (forest or city), pure white background, surreal blending, True Detective intro style, sharp outline.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },

    // LANDSCAPE & ARCHITECTURE
    { id: "burkard-coast", title: "Chris Burkard", category: "Landscape", desc: "Cold coast, minimal palettes.", data: { genre: "landscape", camera: "Sony A7R V", lens: "16-35mm wide", focal: 16, aperture: "f/5.6", shutter: "1/1000s", iso: "400", lighting: "Soft Overcast", composition: "Wide Establishing", lightingSetups: [], vibe: "Chris Burkard style, cold water surf photography, sub-arctic landscape (Iceland/Norway), tiny human scale against massive nature, moody storm light, desaturated greens and blues, sharp digital resolution.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Cool Shade", grain: "Clean/No Grain" } },
    { id: "adams-bw", title: "Ansel Adams", category: "Landscape", desc: "Epic B&W mountains, Zone System.", data: { genre: "landscape", camera: "Deardorff 8x10", lens: "300mm prime (8x10 eq)", focal: 300, aperture: "f/64", shutter: "1s", iso: "25", lighting: "Natural Light", composition: "Leading Lines", lightingSetups: [], vibe: "Ansel Adams style, Zone System exposure (full tonal range), deep black skies created by Wratten 25A Red Filter, dramatic white clouds, high contrast dodging and burning, f/64 group aesthetic, infinite depth of field, sharp gelatin silver print.", lensChar: "Clinical Sharp", film: "B&W Sheet Film", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "sugimoto-minimal", title: "Hiroshi Sugimoto", category: "Landscape", desc: "Ultra-minimal long exposure.", data: { genre: "landscape", camera: "Deardorff 8x10", lens: "300mm prime", focal: 300, aperture: "f/45", shutter: "Bulb", iso: "100", lighting: "Natural Light", composition: "Centered", lightingSetups: [], vibe: "Hiroshi Sugimoto style (Seascapes), horizon line perfectly bisecting the frame, long exposure blurring water into mist, seamless gradient between sky and sea, ultra-fine grain 8x10 sheet film aesthetic, timeless stillness, Zen minimalism.", lensChar: "Clinical Sharp", film: "B&W Sheet Film", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "kenna-minimal", title: "Michael Kenna", category: "Landscape", desc: "Quiet monochrome, fog.", data: { genre: "landscape", camera: "Hasselblad 500C/M", lens: "150mm prime", focal: 150, aperture: "f/22", shutter: "30s", iso: "400", lighting: "Natural Light", composition: "Centered", lightingSetups: [], vibe: "Michael Kenna style, minimalist long exposure landscapes, quiet geometry, fog or snow, deep blacks and glowing white highlights (reciprocity failure effect), square 6x6 format composition, solitude, ethereal atmosphere, high contrast black and white.", lensChar: "Vintage Softness", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Heavy Grit" } }, { id: "shulman-midcentury-arch", title: "Julius Shulman", category: "Architecture", desc: "Clean mid-century hero shots.", data: { genre: "architecture", camera: "Large Format 4x5", lens: "90mm wide", focal: 90, aperture: "f/22", shutter: "1/15s", iso: "50", lighting: "Natural Light", composition: "Symmetrical Arch", lightingSetups: ["window side light, soft falloff"], vibe: "Julius Shulman style, mid‑century modern hero shots, razor detail, corrected verticals, crisp daylight, black and white architectural mastery.", lensChar: "Clinical Sharp", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "baan-livedin-arch", title: "Iwan Baan", category: "Architecture", desc: "Documentary lived-in spaces.", data: { genre: "architecture", camera: "Canon EOS R5 II", lens: "24-70mm zoom", focal: 24, aperture: "f/5.6", shutter: "1/250s", iso: "800", lighting: "Natural Light", composition: "Rule of Thirds", vibe: "Iwan Baan style, documentary architecture, buildings shown as lived spaces, natural light only, candid human activity.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "stoller-clarity", title: "Ezra Stoller", category: "Architecture", desc: "Clean orthogonal hero shots.", data: { genre: "architecture", camera: "Deardorff 8x10", lens: "90mm wide (8x10 eq)", focal: 90, aperture: "f/64", shutter: "1s", iso: "25", lighting: "Natural Light", composition: "Symmetrical Arch", lightingSetups: [], vibe: "Ezra Stoller style, meticulous architectural documentation, parallel verticals, crisp mid-century modern clarity, calm daylight, deep focus.", lensChar: "Clinical Sharp", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "binet-poetry", title: "Hélène Binet", category: "Architecture", desc: "Deep shadow poetry.", data: { genre: "architecture", camera: "Large Format 4x5", lens: "150mm prime", focal: 150, aperture: "f/16", shutter: "1/60s", iso: "100", lighting: "Natural Light", composition: "Leading Lines", lightingSetups: [], vibe: "Hélène Binet style, architectural photography as light study, deep shadows, beams of sun, quiet human presence for scale, poetic abstraction.", lensChar: "Vintage Softness", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "guerra-living", title: "Fernando Guerra", category: "Architecture", desc: "Warm lived-in architecture.", data: { genre: "architecture", camera: "Canon EOS R5 II", lens: "16-35mm wide", focal: 20, aperture: "f/5.6", shutter: "1/250s", iso: "400", lighting: "Natural Light", composition: "Wide Establishing", lightingSetups: [], vibe: "Fernando Guerra style, lived-in architecture with people and everyday motion, warm daylight, rich materials, balanced wide framing.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "hufton-crow", title: "Hufton + Crow", category: "Architecture", desc: "Crisp contemporary geometry.", data: { genre: "architecture", camera: "Phase One XF IQ4", lens: "28mm wide", focal: 28, aperture: "f/11", shutter: "1/125s", iso: "50", lighting: "Natural Light", composition: "Symmetrical Arch", lightingSetups: [], vibe: "Hufton + Crow style, clean contemporary architecture, precise lines, high dynamic range daylight, powerful scale and geometry.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "attali-landscape", title: "Erieta Attali", category: "Architecture", desc: "Buildings as terrain.", data: { genre: "architecture", camera: "Hasselblad 500C/M", lens: "50mm wide", focal: 50, aperture: "f/8", shutter: "1/125s", iso: "100", lighting: "Golden Hour", composition: "Layered Depth", lightingSetups: [], vibe: "Erieta Attali style, architecture embedded in landscape, golden hour tones, long shadows, subtle atmosphere, calm cinematic wide framing.", lensChar: "Vintage Softness", film: "Kodak Portra 160", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "basilico-rigor", title: "Gabriele Basilico", category: "Architecture", desc: "Urban rigor, cool monochrome.", data: { genre: "architecture", camera: "Large Format 4x5", lens: "90mm wide", focal: 90, aperture: "f/22", shutter: "1/30s", iso: "100", lighting: "Soft Overcast", composition: "Symmetrical Arch", lightingSetups: [], vibe: "Gabriele Basilico style, rigorous cityscapes, calm frontal viewpoints, ordered grids, soft overcast light, precise black and white tonality.", lensChar: "Clinical Sharp", film: "Kodak Tri-X 400", wb: "Daylight Balanced", grain: "Subtle Grain" } },

    // PRODUCT & LIFESTYLE
    { id: "brandl-packshot", title: "Karl Taylor", category: "Product", desc: "High-end commercial packshot with sculptural lighting.", data: { genre: "product", camera: "Hasselblad H6D-100c", lens: "Hasselblad HC 120mm Macro II", focal: 120, aperture: "f/16", shutter: "1/125s", iso: "64", lighting: "Gradient Scrims / Backlit", composition: "Centered & Symmetrical", lightingSetups: ["Large diffusion sheet behind product (Transillumination)", "Black flags (Negative Fill) on sides to define edges", "Gradient light painted on glossy surfaces"], vibe: "Premium ecommerce, 'sculpted' light rather than flat light, perfect edge definition via negative fill, glossy reflections, clinical color accuracy, 3D dimensionality on a white background.", lensChar: "Clinical & Distortion-Free", film: "16-bit Digital Raw", wb: "5500K (Flash)", grain: "Zero Grain", productSubgenre: "Cosmetics / Liquids" } },
    { id: "kleiner-playful-stilllife", title: "Carl Kleiner", category: "Product", desc: "Geometric, colorful, playful.", data: { genre: "product", camera: "Hasselblad X2D 100C", lens: "90mm prime", focal: 90, aperture: "f/11", shutter: "1/125s", iso: "64", lighting: "Studio Softbox", composition: "Top-down Flat Lay", lightingSetups: ["dual softbox symmetric lighting", "gradient sweep background, tabletop product lighting"], vibe: "Carl Kleiner style, vibrant geometric still life, clean color blocking, handmade objects, graphic precision.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain", productSubgenre: "Tabletop Styled" } },
    { id: "kander-editorial-polish", title: "Nadav Kander", category: "Product", desc: "Quiet, large-format polish.", data: { genre: "product", camera: "Large Format 4x5", lens: "150mm prime", focal: 150, aperture: "f/22", shutter: "1/15s", iso: "100", lighting: "Studio Softbox", composition: "Centered", lightingSetups: ["softbox key plus bounce", "top down scrim, negative fill"], vibe: "Nadav Kander style, large-format stillness and editorial polish, restrained color, sculpted shadows, spacious negative space.", lensChar: "Vintage Softness", film: "Kodak Portra 400", wb: "Daylight Balanced", grain: "Subtle Grain", productSubgenre: "Luxury Jewelry Macro" } },
    { id: "illenberger-surreal-tabletop", title: "Sarah Illenberger", category: "Product", desc: "Cheerful, surreal objects.", data: { genre: "product", camera: "Canon EOS R5 II", lens: "50mm prime", focal: 50, aperture: "f/8", shutter: "1/125s", iso: "100", lighting: "High Key White Cyc", composition: "Asymmetric Framing", lightingSetups: ["high key white cyc, even wraparound light", "backlit translucent diffusion, soft halos"], vibe: "Sarah Illenberger style, playful surreal product concepts, everyday objects turned into witty visual puns, vivid color.", lensChar: "Dreamy Bloom", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain", productSubgenre: "Tabletop Styled" } },
    { id: "koloskov-gloss", title: "Alex Koloskov", category: "Product", desc: "High-gloss premium product.", data: { genre: "product", camera: "Phase One XF IQ4", lens: "120mm macro", focal: 120, aperture: "f/22", shutter: "1/125s", iso: "50", lighting: "Hard Strobe", composition: "Tight Close-up", productSubgenre: "Tech Gadget Hero", lightingSetups: ["cross-polarized lighting to control reflections", "strip rim light, edge definition", "gradient sweep background, tabletop product lighting"], vibe: "Alex Koloskov style, crisp product hero imagery, sculpted reflections, deep blacks and clean gradients.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "belanger-minimal", title: "Peter Belanger", category: "Product", desc: "Clean Apple-like minimal.", data: { genre: "product", camera: "Canon EOS R5 II", lens: "100mm macro", focal: 100, aperture: "f/11", shutter: "1/160s", iso: "100", lighting: "High Key White Cyc", composition: "Centered", productSubgenre: "Tech Gadget Hero", lightingSetups: ["high key white cyc, even wraparound light", "softbox key plus bounce"], vibe: "Peter Belanger style, ultra-clean minimal product hero shots, soft controlled wrap light, seamless backgrounds, Apple advertising aesthetic.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "hogan-speed", title: "Timothy Hogan", category: "Product", desc: "High-speed liquids.", data: { genre: "product", camera: "Canon EOS R5 II", lens: "100mm macro", focal: 100, aperture: "f/16", shutter: "1/4000s", iso: "800", lighting: "Hard Strobe", composition: "Tight Close-up", productSubgenre: "Beverage Condensation", lightingSetups: ["strip rim light, edge definition", "gradient sweep background, tabletop product lighting"], vibe: "Timothy Hogan style, high-speed tabletop liquids, crisp freeze, luminous gels and splashes, tight macro detail.", lensChar: "Clinical Sharp", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Clean/No Grain" } },
    { id: "hargreaves-food", title: "Henry Hargreaves", category: "Product", desc: "Conceptual food still life.", data: { genre: "product", camera: "Canon EOS 5D Mark IV", lens: "50mm prime", focal: 50, aperture: "f/8", shutter: "1/125s", iso: "200", lighting: "Studio Softbox", composition: "Top-down Flat Lay", productSubgenre: "Food Editorial", lightingSetups: ["top down scrim, negative fill"], vibe: "Henry Hargreaves style, concept-first food still life, clean tabletop geometry, editorial humor, soft directional studio light.", lensChar: "Vintage Softness", film: "Digital Sensor", wb: "Daylight Balanced", grain: "Subtle Grain" } },
    { id: "parker-poetic", title: "Olivia Parker", category: "Product", desc: "Quiet symbolic still life.", data: { genre: "product", camera: "Large Format 4x5", lens: "210mm prime", focal: 210, aperture: "f/22", shutter: "1/8s", iso: "100", lighting: "Natural Light", composition: "Leading Lines", productSubgenre: "Tabletop Styled", lightingSetups: ["window side light, soft falloff"], vibe: "Olivia Parker style, poetic symbolic still life, gentle window light, carefully arranged objects with quiet narrative, split toning.", lensChar: "Vintage Softness", film: "Polaroid Type 55", wb: "Daylight Balanced", grain: "Subtle Grain" } },
];
